/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package distsys.retail_ca;
import io.grpc.stub.StreamObserver;
import javax.swing.JCheckBox;
import generated.grpc.retailorderservice.Product;
import generated.grpc.retailorderservice.Order;
import generated.grpc.retailopendoorservice.Payment;
import generated.grpc.retailopendoorservice.Door;

/*
 *
 * @author yuyua
 */
public class RetailGUI extends javax.swing.JFrame {
    private JCheckBox[] products;
    private RetailOrderClient retailOrderClient;
    private RetailPayByOrderClient retailPayByOrderClient;
    private RetailOpenDoorClient retailOpenDoorClient;

    /**
     * Creates new form RetailGUI
     */
    public RetailGUI() {
        initComponents();
        initProducts();
        initRadio();
        retailOrderClient = new RetailOrderClient();
        retailPayByOrderClient = new RetailPayByOrderClient();
        retailOpenDoorClient = new RetailOpenDoorClient();
    }
    private void initProducts(){
        products = new JCheckBox[]{
            productTextField1,
            productTextField2,
            productTextField3,
            productTextField4,
            productTextField5,
            productTextField6
        };
    }
    
    private void initRadio(){
        doorNumberTextField.add(doorNum1);
        doorNumberTextField.add(doorNum2);
        doorNumberTextField.add(doorNum3);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        doorNumberTextField = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        productsLabel = new javax.swing.JLabel();
        productTextField1 = new javax.swing.JCheckBox();
        productTextField2 = new javax.swing.JCheckBox();
        productTextField3 = new javax.swing.JCheckBox();
        productTextField4 = new javax.swing.JCheckBox();
        productTextField5 = new javax.swing.JCheckBox();
        productTextField6 = new javax.swing.JCheckBox();
        orderCreateButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        createOrderResult11 = new javax.swing.JTextArea();
        orderIdLabel = new javax.swing.JLabel();
        orderCheckButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        createOrderResult12 = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        payServiceOrderIdTextField21 = new javax.swing.JTextField();
        payButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        payServiceResult21 = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        payServiceOrderIdTextField22 = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        payServiceResult22 = new javax.swing.JTextArea();
        payCheckButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        OrderServiceOrderIdTextField12 = new javax.swing.JTextField();
        PaymentNosLabel = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        paymentNosTextField31 = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        paymentNoTextField32 = new javax.swing.JTextField();
        doorCheckButton = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        doorServiceResult31 = new javax.swing.JTextArea();
        doorOpenButton = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        doorServiceResult32 = new javax.swing.JTextArea();
        runOrderServiceButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        doorNum1 = new javax.swing.JRadioButton();
        doorNum3 = new javax.swing.JRadioButton();
        doorNum2 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText(" AddOrder");

        jLabel2.setText("GetProductsByOrderId");

        jLabel3.setText("CreatePayment");

        jLabel4.setText("GetPaymentByOrderId");

        jLabel5.setText(" CheckDoorStatus");

        jLabel6.setText("DoorService OpenDoor");

        productsLabel.setText("products:");

        productTextField1.setText("chips");

        productTextField2.setText("nuts");

        productTextField3.setText("candy");

        productTextField4.setText("cookies");

        productTextField5.setText("apple");

        productTextField6.setText("orange");

        orderCreateButton.setText("Create Order");
        orderCreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderCreateButtonActionPerformed(evt);
            }
        });

        createOrderResult11.setColumns(20);
        createOrderResult11.setRows(5);
        jScrollPane1.setViewportView(createOrderResult11);

        orderIdLabel.setText("OrderID:");

        orderCheckButton.setText("Check");
        orderCheckButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderCheckButtonActionPerformed(evt);
            }
        });

        createOrderResult12.setColumns(20);
        createOrderResult12.setRows(5);
        jScrollPane2.setViewportView(createOrderResult12);

        jLabel9.setText("OrderID:");

        payServiceOrderIdTextField21.setText("orderNo_8455c095-1ac8-4b35-a9f7-6b6a6e146931");

        payButton.setText("Pay");
        payButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payButtonActionPerformed(evt);
            }
        });

        payServiceResult21.setColumns(20);
        payServiceResult21.setRows(5);
        jScrollPane3.setViewportView(payServiceResult21);

        jLabel11.setText("OrderID:");

        payServiceOrderIdTextField22.setText("orderNo_8455c095-1ac8-4b35-a9f7-6b6a6e1469312");

        payServiceResult22.setColumns(20);
        payServiceResult22.setRows(5);
        jScrollPane4.setViewportView(payServiceResult22);

        payCheckButton.setText("Check");
        payCheckButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payCheckButtonActionPerformed(evt);
            }
        });

        OrderServiceOrderIdTextField12.setText("orderNo_8455c095-1ac8-4b35-a9f7-6b6a6e146931");
        OrderServiceOrderIdTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderServiceOrderIdTextField12ActionPerformed(evt);
            }
        });

        PaymentNosLabel.setText("PaymentNos:");

        paymentNosTextField31.setColumns(20);
        paymentNosTextField31.setRows(5);
        paymentNosTextField31.setText("payNo_ac8-4b35-a9f7-6b6a6e1469312,payNo_ac8-4b35-a9f7-6b6a6e1469311");
        jScrollPane5.setViewportView(paymentNosTextField31);

        jLabel14.setText("PaymentNo:");

        paymentNoTextField32.setText("payNo_ac8-4b35-a9f7-6b6a6e1469300");

        doorCheckButton.setText("Check");
        doorCheckButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doorCheckButtonActionPerformed(evt);
            }
        });

        doorServiceResult31.setColumns(20);
        doorServiceResult31.setRows(5);
        jScrollPane6.setViewportView(doorServiceResult31);

        doorOpenButton.setText("Open");
        doorOpenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doorOpenButtonActionPerformed(evt);
            }
        });

        doorServiceResult32.setColumns(20);
        doorServiceResult32.setRows(5);
        jScrollPane7.setViewportView(doorServiceResult32);

        runOrderServiceButton.setBackground(new java.awt.Color(153, 204, 255));
        runOrderServiceButton.setForeground(new java.awt.Color(0, 0, 0));
        runOrderServiceButton.setText("Run All Service");
        runOrderServiceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runOrderServiceButtonActionPerformed(evt);
            }
        });

        jLabel7.setText("Door Number:");

        doorNum1.setText("1");

        doorNum3.setText("3");

        doorNum2.setText("2");
        doorNum2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doorNum2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 849, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(productsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(orderCreateButton)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(payButton)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(payServiceOrderIdTextField21, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(219, 219, 219)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(payServiceOrderIdTextField22, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(payCheckButton)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(98, 98, 98)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(doorOpenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel7)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel14)
                                    .addGap(71, 71, 71)
                                    .addComponent(paymentNoTextField32, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(PaymentNosLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(doorCheckButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(134, 134, 134)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(170, 170, 170)
                                .addComponent(doorNum1)
                                .addGap(18, 18, 18)
                                .addComponent(doorNum2)
                                .addGap(18, 18, 18)
                                .addComponent(doorNum3))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(152, 152, 152)
                                .addComponent(jLabel6))))))
            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 769, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(productTextField1)
                        .addGap(0, 0, 0)
                        .addComponent(productTextField2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(productTextField3))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(runOrderServiceButton)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(productTextField4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(productTextField5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(productTextField6)
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(orderIdLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(OrderServiceOrderIdTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(orderCheckButton)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jLabel2))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(runOrderServiceButton)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(productsLabel)
                            .addComponent(productTextField1)
                            .addComponent(productTextField2)
                            .addComponent(productTextField3)
                            .addComponent(productTextField4)
                            .addComponent(productTextField5)
                            .addComponent(productTextField6)
                            .addComponent(orderIdLabel)
                            .addComponent(OrderServiceOrderIdTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(orderCheckButton))
                    .addComponent(orderCreateButton, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(payServiceOrderIdTextField21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(payServiceOrderIdTextField22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(payButton)
                    .addComponent(payCheckButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PaymentNosLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(doorCheckButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(paymentNoTextField32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(doorNum2)
                            .addComponent(doorNum1)
                            .addComponent(doorNum3)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(doorOpenButton)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void orderCreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderCreateButtonActionPerformed
        // TODO add your handling code here:        
        StreamObserver<generated.grpc.retailorderservice.Order> responseObserver = new StreamObserver<generated.grpc.retailorderservice.Order>(){
            @Override
            public void onNext(generated.grpc.retailorderservice.Order order){
                //accept the orderNo
//                System.out.println("RetailOrderService has return the orderNo: "+order.getOrderNo());
                createOrderResult11.setText("RetailOrderService has return the orderNo: "+order.getOrderNo());
            }

            @Override
            public void onError(Throwable t){
                t.printStackTrace();
            }
            
            @Override            
            public void onCompleted(){
                System.out.println("This RetailOrderService is Completed!");
            }
        };
        StreamObserver<Product> requestObserver = retailOrderClient.asyncStub.addOrderByProducts(responseObserver);
       
        for(JCheckBox product : products) {
            if(product.isSelected()) {
                try{
                    requestObserver.onNext(Product.newBuilder().setProductName(product.getText()).build());
                    Thread.sleep(500);
                 }catch(Exception e){
                    e.printStackTrace();
                 }
            }
        }
        requestObserver.onCompleted();
    }//GEN-LAST:event_orderCreateButtonActionPerformed

    /**
     * OrderService
     * @param evt 
     */
    private void orderCheckButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderCheckButtonActionPerformed
        // TODO add your handling code here:
        // Get products by orderID
        String orderNo = OrderServiceOrderIdTextField12.getText();
        Order request = Order.newBuilder().setOrderNo(orderNo).build();
        StreamObserver<Product> response = new StreamObserver<Product>(){
           @Override
           public void onNext(Product p){
               //GET productId and productName
//               System.out.println("Product{id="+p.getProductId()+", name="+p.getProductName()+";}");
               createOrderResult12.setText(createOrderResult12.getText()+"Product{id="+p.getProductId()+", name="+p.getProductName()+";}\r");
           }
           
           @Override
           public void onError(Throwable t){
               t.printStackTrace();
           }
           
           @Override
           public void onCompleted(){
               System.out.println("This RetailOrderService is Completed!");
           }
       };
       retailOrderClient.asyncStub.getProductsByOrderNo(request, response);
       try{
            Thread.sleep(1000);
       }catch(Exception e){
            e.printStackTrace();
       }
        
    }//GEN-LAST:event_orderCheckButtonActionPerformed

    private void OrderServiceOrderIdTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderServiceOrderIdTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OrderServiceOrderIdTextField12ActionPerformed

    /**
     * PayByOrderService 
     * CreatePayment
     * @param evt 
     */
    private void payButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payButtonActionPerformed
        // TODO add your handling code here:
        String orderId = payServiceOrderIdTextField21.getText();
        String message = retailPayByOrderClient.requestPayByOrderId(orderId);
        payServiceResult21.setText(message);
//        System.out.println("Receied the newest paymentNo is "+response.getPayNo());
    }//GEN-LAST:event_payButtonActionPerformed

    /**
     * PayByOrderIdService
     * GetPaymentByOrderId
     * @param evt 
     */
    private void payCheckButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payCheckButtonActionPerformed
        // TODO add your handling code here:
        String orderId = payServiceOrderIdTextField22.getText();
        String message = retailPayByOrderClient.getPaymentInfoByOrderNo(orderId);
        payServiceResult22.setText(message);
    }//GEN-LAST:event_payCheckButtonActionPerformed

    /**
     * OpenDoorService
     * Check mutil-door status
     * @param evt 
     */
    private void doorCheckButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doorCheckButtonActionPerformed
        // TODO add your handling code here:
        System.out.println("Bi-directional - getCurrentDoorStatus of RetailOpenDoor");
        StreamObserver<Door> responseObserver = new StreamObserver<Door>(){
            @Override
            public void onNext(Door d){
//                doorServiceResult31.getText();
                doorServiceResult31.setText(doorServiceResult31.getText()+"Door{doorNo="+d.getDoorNo()+", doorStatus= "+d.getDStatus()+"}\r");
//                System.out.println("Door{doorNo="+d.getDoorNo()+", doorStatus= "+d.getDStatus()+"}");
            }
            
            @Override
            public void onError(Throwable t){
                t.printStackTrace();
            }
            
            @Override
            public void onCompleted(){
                System.out.println("Bi-directional - getCurrentDoorStatus of RetailOpenDoor is completed!");
            }
        };
        
        StreamObserver<Payment> request = retailOpenDoorClient.asyncStub.currentDoorStatus(responseObserver);
        try{
            String paymentNos = paymentNosTextField31.getText();
            String[] paymentNosStr = paymentNos.split(",");
            for(String paymentNo: paymentNosStr){
                request.onNext(Payment.newBuilder().setPayNo(paymentNo).build());
                Thread.sleep(500);
            }
            request.onCompleted();
            Thread.sleep(500);
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_doorCheckButtonActionPerformed
    /**
     * OpenDoorService
     * Open the specific door
     * @param evt 
     */
    private void doorOpenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doorOpenButtonActionPerformed
        // TODO add your handling code here:
        String paymentNo = paymentNoTextField32.getText();
        int doorNum;
        if (doorNum1.isSelected()) {
            doorNum = 1;
        } else if (doorNum1.isSelected()) {
            doorNum = 2;
        }else{
            doorNum = 3;
        }
        String message = retailOpenDoorClient.requestOpenDoor(doorNum, paymentNo);
        doorServiceResult32.setText(message);
    }//GEN-LAST:event_doorOpenButtonActionPerformed

    /**
     * run OrderService
     * @param evt 
     */
    private void runOrderServiceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runOrderServiceButtonActionPerformed
        // TODO add your handling code here:
        RetailOrderService.main(new String[]{});
        RetailPayByOrderService.main(new String[]{});
        RetailOpenDoorService.main(new String[]{});
    }//GEN-LAST:event_runOrderServiceButtonActionPerformed

    private void doorNum2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doorNum2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doorNum2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RetailGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RetailGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RetailGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RetailGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RetailGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField OrderServiceOrderIdTextField12;
    private javax.swing.JLabel PaymentNosLabel;
    private javax.swing.JTextArea createOrderResult11;
    private javax.swing.JTextArea createOrderResult12;
    private javax.swing.JButton doorCheckButton;
    private javax.swing.JRadioButton doorNum1;
    private javax.swing.JRadioButton doorNum2;
    private javax.swing.JRadioButton doorNum3;
    private javax.swing.ButtonGroup doorNumberTextField;
    private javax.swing.JButton doorOpenButton;
    private javax.swing.JTextArea doorServiceResult31;
    private javax.swing.JTextArea doorServiceResult32;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton orderCheckButton;
    private javax.swing.JButton orderCreateButton;
    private javax.swing.JLabel orderIdLabel;
    private javax.swing.JButton payButton;
    private javax.swing.JButton payCheckButton;
    private javax.swing.JTextField payServiceOrderIdTextField21;
    private javax.swing.JTextField payServiceOrderIdTextField22;
    private javax.swing.JTextArea payServiceResult21;
    private javax.swing.JTextArea payServiceResult22;
    private javax.swing.JTextField paymentNoTextField32;
    private javax.swing.JTextArea paymentNosTextField31;
    private javax.swing.JCheckBox productTextField1;
    private javax.swing.JCheckBox productTextField2;
    private javax.swing.JCheckBox productTextField3;
    private javax.swing.JCheckBox productTextField4;
    private javax.swing.JCheckBox productTextField5;
    private javax.swing.JCheckBox productTextField6;
    private javax.swing.JLabel productsLabel;
    private javax.swing.JButton runOrderServiceButton;
    // End of variables declaration//GEN-END:variables
}
